global proc string HexifyFloats( string $line, int $fulloutput ){
    $php_exe = "D:/Apps/php-7.1/php";
    $command = "require_once \'Helper.php\';";
    $command += "HexifyFloats::invokeViaCLI( \'" + $line + "\' );";
    $systemcommand = $php_exe+" -r \""+$command+"\";";
    if( $fulloutput )
    {
        print $systemcommand;
        print "\n";
    }
    $out = system($systemcommand);
    if( $fulloutput )
    {
        print $out;
        print "\n";
    }
    return $out;
}